name: Build and Test Docker Container

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t huri_project .
          echo "Built Docker image"

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name huri_container huri_project
          echo "Started Docker container"
          
          sleep 30
          docker logs huri_container
          curl http://127.0.0.1:5000/


      - name: Stop Docker container
        run: docker stop huri_container
